---
# tasks file for apache

- name: Install Apache
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true
  become: true

- name: Enable and start Apache service
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true
  become: true

- name: Ensure mod_rewrite is enabled
  ansible.builtin.command: a2enmod rewrite
  args:
    creates: /etc/apache2/mods-enabled/rewrite.load
  notify: Reload Apache
  become: true

- name: Deploy Apache vhost configuration
  ansible.builtin.template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload Apache
  become: true
