- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install base packages
  apt:
    name:
      - curl
      - unzip
      - software-properties-common
    state: present
  become: true
