- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
  become: true

- name: Start MySQL
  service:
    name: mysql
    state: started
    enabled: true
  become: true

- name: Create demo DB
  shell: mysql -uroot -e "CREATE DATABASE IF NOT EXISTS demoapp;"
  become: true

- name: Create demo DB user
  shell: |
    mysql -uroot -e "CREATE USER IF NOT EXISTS 'demo_user'@'%' IDENTIFIED BY 'demo_pass';"
    mysql -uroot -e "GRANT ALL PRIVILEGES ON demoapp.* TO 'demo_user'@'%'; FLUSH PRIVILEGES;"
  become: true
