- name: Install PHP and extensions
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
      - php-cli
      - php-curl
      - php-xml
      - php-mbstring
    state: present
  become: true
