- name: Install ufw
  apt:
    name: ufw
    state: present
  become: true

- name: Allow OpenSSH
  ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Allow HTTP
  ufw:
    rule: allow
    port: '80'
    proto: tcp
  become: true

- name: Enable UFW
  ufw:
    state: enabled
  become: true

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present
  become: true

- name: Ensure fail2ban is enabled and running
  service:
    name: fail2ban
    state: started
    enabled: true
  become: true
