- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

- name: Allow OpenSSH
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
  become: true

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: true

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
  become: true

- name: Ensure fail2ban is enabled and running
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  become: true
